name: Playwright Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: test_automation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
